language: rust

rust:
  - 1.22.1
  - stable
  - beta
  - nightly

cache: cargo

before_script: (cargo install rustfmt || true)

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email:
    on_success: never
